// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nptmzqetvlzfhoisubav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdG16cWV0dmx6ZmhvaXN1YmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzA0MDIsImV4cCI6MjA3MTU0NjQwMn0.KghgdtmBs-6VyYWxxmfIxVMd9aEnouBgYOlNmPMVEPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});